/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthViewRouteImport } from './routes/$authView'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/_user'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as PublicProductsProductIdRouteImport } from './routes/_public/products/$productId'
import { Route as AuthenticatedUserCartRouteImport } from './routes/_authenticated/_user/cart'
import { Route as AuthenticatedUserProfileIndexRouteImport } from './routes/_authenticated/_user/profile/index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedAdminAdminProductsRouteImport } from './routes/_authenticated/_admin/admin/products'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthViewRoute = AuthViewRouteImport.update({
  id: '/$authView',
  path: '/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/_public/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserCartRoute = AuthenticatedUserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedUserProfileIndexRoute =
  AuthenticatedUserProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminProductsRoute =
  AuthenticatedAdminAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$authView': typeof AuthViewRoute
  '/cart': typeof AuthenticatedUserCartRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/profile': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$authView': typeof AuthViewRoute
  '/cart': typeof AuthenticatedUserCartRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/profile': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$authView': typeof AuthViewRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_user': typeof AuthenticatedUserRouteWithChildren
  '/_authenticated/_user/cart': typeof AuthenticatedUserCartRoute
  '/_public/products/$productId': typeof PublicProductsProductIdRoute
  '/_authenticated/_admin/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_user/profile/': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$authView'
    | '/cart'
    | '/products/$productId'
    | '/admin/products'
    | '/admin'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$authView'
    | '/cart'
    | '/products/$productId'
    | '/admin/products'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/$authView'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/_user'
    | '/_authenticated/_user/cart'
    | '/_public/products/$productId'
    | '/_authenticated/_admin/admin/products'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_user/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthViewRoute: typeof AuthViewRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$authView': {
      id: '/$authView'
      path: '/$authView'
      fullPath: '/$authView'
      preLoaderRoute: typeof AuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/products/$productId': {
      id: '/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_user/cart': {
      id: '/_authenticated/_user/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedUserCartRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/profile/': {
      id: '/_authenticated/_user/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedUserProfileIndexRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/products': {
      id: '/_authenticated/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminProductsRoute: typeof AuthenticatedAdminAdminProductsRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminProductsRoute: AuthenticatedAdminAdminProductsRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserCartRoute: typeof AuthenticatedUserCartRoute
  AuthenticatedUserProfileIndexRoute: typeof AuthenticatedUserProfileIndexRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserCartRoute: AuthenticatedUserCartRoute,
  AuthenticatedUserProfileIndexRoute: AuthenticatedUserProfileIndexRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthViewRoute: AuthViewRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
